// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: iwebgw.proto

package iwebgw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// 외부 데이터 처리 요청 메시지
type IWebGWCallRegistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	UserAni       string                 `protobuf:"bytes,3,opt,name=user_ani,json=userAni,proto3" json:"user_ani,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IWebGWCallRegistReq) Reset() {
	*x = IWebGWCallRegistReq{}
	mi := &file_iwebgw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IWebGWCallRegistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWebGWCallRegistReq) ProtoMessage() {}

func (x *IWebGWCallRegistReq) ProtoReflect() protoreflect.Message {
	mi := &file_iwebgw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWebGWCallRegistReq.ProtoReflect.Descriptor instead.
func (*IWebGWCallRegistReq) Descriptor() ([]byte, []int) {
	return file_iwebgw_proto_rawDescGZIP(), []int{0}
}

func (x *IWebGWCallRegistReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IWebGWCallRegistReq) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *IWebGWCallRegistReq) GetUserAni() string {
	if x != nil {
		return x.UserAni
	}
	return ""
}

type IWebGWCallRegistRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IWebGWCallRegistRes) Reset() {
	*x = IWebGWCallRegistRes{}
	mi := &file_iwebgw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IWebGWCallRegistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWebGWCallRegistRes) ProtoMessage() {}

func (x *IWebGWCallRegistRes) ProtoReflect() protoreflect.Message {
	mi := &file_iwebgw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWebGWCallRegistRes.ProtoReflect.Descriptor instead.
func (*IWebGWCallRegistRes) Descriptor() ([]byte, []int) {
	return file_iwebgw_proto_rawDescGZIP(), []int{1}
}

func (x *IWebGWCallRegistRes) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *IWebGWCallRegistRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IWebGWCallRegistRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *IWebGWCallRegistRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IWebGWCallUnRegistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IWebGWCallUnRegistReq) Reset() {
	*x = IWebGWCallUnRegistReq{}
	mi := &file_iwebgw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IWebGWCallUnRegistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWebGWCallUnRegistReq) ProtoMessage() {}

func (x *IWebGWCallUnRegistReq) ProtoReflect() protoreflect.Message {
	mi := &file_iwebgw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWebGWCallUnRegistReq.ProtoReflect.Descriptor instead.
func (*IWebGWCallUnRegistReq) Descriptor() ([]byte, []int) {
	return file_iwebgw_proto_rawDescGZIP(), []int{2}
}

func (x *IWebGWCallUnRegistReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IWebGWCallUnRegistReq) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type IWebGWCallUnRegistRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IWebGWCallUnRegistRes) Reset() {
	*x = IWebGWCallUnRegistRes{}
	mi := &file_iwebgw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IWebGWCallUnRegistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWebGWCallUnRegistRes) ProtoMessage() {}

func (x *IWebGWCallUnRegistRes) ProtoReflect() protoreflect.Message {
	mi := &file_iwebgw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWebGWCallUnRegistRes.ProtoReflect.Descriptor instead.
func (*IWebGWCallUnRegistRes) Descriptor() ([]byte, []int) {
	return file_iwebgw_proto_rawDescGZIP(), []int{3}
}

func (x *IWebGWCallUnRegistRes) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *IWebGWCallUnRegistRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IWebGWCallUnRegistRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IWebGWRequestPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PageFilename  string                 `protobuf:"bytes,4,opt,name=page_filename,json=pageFilename,proto3" json:"page_filename,omitempty"`
	PageData      string                 `protobuf:"bytes,5,opt,name=page_data,json=pageData,proto3" json:"page_data,omitempty"`
	Bargin        bool                   `protobuf:"varint,6,opt,name=bargin,proto3" json:"bargin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IWebGWRequestPageReq) Reset() {
	*x = IWebGWRequestPageReq{}
	mi := &file_iwebgw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IWebGWRequestPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWebGWRequestPageReq) ProtoMessage() {}

func (x *IWebGWRequestPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_iwebgw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWebGWRequestPageReq.ProtoReflect.Descriptor instead.
func (*IWebGWRequestPageReq) Descriptor() ([]byte, []int) {
	return file_iwebgw_proto_rawDescGZIP(), []int{4}
}

func (x *IWebGWRequestPageReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IWebGWRequestPageReq) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *IWebGWRequestPageReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *IWebGWRequestPageReq) GetPageFilename() string {
	if x != nil {
		return x.PageFilename
	}
	return ""
}

func (x *IWebGWRequestPageReq) GetPageData() string {
	if x != nil {
		return x.PageData
	}
	return ""
}

func (x *IWebGWRequestPageReq) GetBargin() bool {
	if x != nil {
		return x.Bargin
	}
	return false
}

type IWebGWRequestPageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IWebGWRequestPageRes) Reset() {
	*x = IWebGWRequestPageRes{}
	mi := &file_iwebgw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IWebGWRequestPageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWebGWRequestPageRes) ProtoMessage() {}

func (x *IWebGWRequestPageRes) ProtoReflect() protoreflect.Message {
	mi := &file_iwebgw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWebGWRequestPageRes.ProtoReflect.Descriptor instead.
func (*IWebGWRequestPageRes) Descriptor() ([]byte, []int) {
	return file_iwebgw_proto_rawDescGZIP(), []int{5}
}

func (x *IWebGWRequestPageRes) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *IWebGWRequestPageRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IWebGWRequestPageRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IWebGWDisconnectWebReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IWebGWDisconnectWebReq) Reset() {
	*x = IWebGWDisconnectWebReq{}
	mi := &file_iwebgw_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IWebGWDisconnectWebReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWebGWDisconnectWebReq) ProtoMessage() {}

func (x *IWebGWDisconnectWebReq) ProtoReflect() protoreflect.Message {
	mi := &file_iwebgw_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWebGWDisconnectWebReq.ProtoReflect.Descriptor instead.
func (*IWebGWDisconnectWebReq) Descriptor() ([]byte, []int) {
	return file_iwebgw_proto_rawDescGZIP(), []int{6}
}

func (x *IWebGWDisconnectWebReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IWebGWDisconnectWebReq) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *IWebGWDisconnectWebReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type IWebGWDisconnectWebRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IWebGWDisconnectWebRes) Reset() {
	*x = IWebGWDisconnectWebRes{}
	mi := &file_iwebgw_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IWebGWDisconnectWebRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWebGWDisconnectWebRes) ProtoMessage() {}

func (x *IWebGWDisconnectWebRes) ProtoReflect() protoreflect.Message {
	mi := &file_iwebgw_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWebGWDisconnectWebRes.ProtoReflect.Descriptor instead.
func (*IWebGWDisconnectWebRes) Descriptor() ([]byte, []int) {
	return file_iwebgw_proto_rawDescGZIP(), []int{7}
}

func (x *IWebGWDisconnectWebRes) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *IWebGWDisconnectWebRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IWebGWDisconnectWebRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_iwebgw_proto protoreflect.FileDescriptor

const file_iwebgw_proto_rawDesc = "" +
	"\n" +
	"\fiwebgw.proto\x12\x06iwebgw\"f\n" +
	"\x13IWebGWCallRegistReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x19\n" +
	"\buser_ani\x18\x03 \x01(\tR\auserAni\"i\n" +
	"\x13IWebGWCallRegistRes\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"M\n" +
	"\x15IWebGWCallUnRegistReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"U\n" +
	"\x15IWebGWCallUnRegistRes\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\xcd\x01\n" +
	"\x14IWebGWRequestPageReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12#\n" +
	"\rpage_filename\x18\x04 \x01(\tR\fpageFilename\x12\x1b\n" +
	"\tpage_data\x18\x05 \x01(\tR\bpageData\x12\x16\n" +
	"\x06bargin\x18\x06 \x01(\bR\x06bargin\"T\n" +
	"\x14IWebGWRequestPageRes\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"u\n" +
	"\x16IWebGWDisconnectWebReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\"V\n" +
	"\x16IWebGWDisconnectWebRes\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg2\xd2\x02\n" +
	"\x06iwebgw\x12L\n" +
	"\x10IWebGWCallRegist\x12\x1b.iwebgw.IWebGWCallRegistReq\x1a\x1b.iwebgw.IWebGWCallRegistRes\x12R\n" +
	"\x12IWebGWCallUnRegist\x12\x1d.iwebgw.IWebGWCallUnRegistReq\x1a\x1d.iwebgw.IWebGWCallUnRegistRes\x12O\n" +
	"\x11IWebGWRequestPage\x12\x1c.iwebgw.IWebGWRequestPageReq\x1a\x1c.iwebgw.IWebGWRequestPageRes\x12U\n" +
	"\x13IWebGWDisconnectWeb\x12\x1e.iwebgw.IWebGWDisconnectWebReq\x1a\x1e.iwebgw.IWebGWDisconnectWebResB,Z*gitlab.com/ipron-ne/grpc-idl/gen/go/iwebgwb\x06proto3"

var (
	file_iwebgw_proto_rawDescOnce sync.Once
	file_iwebgw_proto_rawDescData []byte
)

func file_iwebgw_proto_rawDescGZIP() []byte {
	file_iwebgw_proto_rawDescOnce.Do(func() {
		file_iwebgw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iwebgw_proto_rawDesc), len(file_iwebgw_proto_rawDesc)))
	})
	return file_iwebgw_proto_rawDescData
}

var file_iwebgw_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_iwebgw_proto_goTypes = []any{
	(*IWebGWCallRegistReq)(nil),    // 0: iwebgw.IWebGWCallRegistReq
	(*IWebGWCallRegistRes)(nil),    // 1: iwebgw.IWebGWCallRegistRes
	(*IWebGWCallUnRegistReq)(nil),  // 2: iwebgw.IWebGWCallUnRegistReq
	(*IWebGWCallUnRegistRes)(nil),  // 3: iwebgw.IWebGWCallUnRegistRes
	(*IWebGWRequestPageReq)(nil),   // 4: iwebgw.IWebGWRequestPageReq
	(*IWebGWRequestPageRes)(nil),   // 5: iwebgw.IWebGWRequestPageRes
	(*IWebGWDisconnectWebReq)(nil), // 6: iwebgw.IWebGWDisconnectWebReq
	(*IWebGWDisconnectWebRes)(nil), // 7: iwebgw.IWebGWDisconnectWebRes
}
var file_iwebgw_proto_depIdxs = []int32{
	0, // 0: iwebgw.iwebgw.IWebGWCallRegist:input_type -> iwebgw.IWebGWCallRegistReq
	2, // 1: iwebgw.iwebgw.IWebGWCallUnRegist:input_type -> iwebgw.IWebGWCallUnRegistReq
	4, // 2: iwebgw.iwebgw.IWebGWRequestPage:input_type -> iwebgw.IWebGWRequestPageReq
	6, // 3: iwebgw.iwebgw.IWebGWDisconnectWeb:input_type -> iwebgw.IWebGWDisconnectWebReq
	1, // 4: iwebgw.iwebgw.IWebGWCallRegist:output_type -> iwebgw.IWebGWCallRegistRes
	3, // 5: iwebgw.iwebgw.IWebGWCallUnRegist:output_type -> iwebgw.IWebGWCallUnRegistRes
	5, // 6: iwebgw.iwebgw.IWebGWRequestPage:output_type -> iwebgw.IWebGWRequestPageRes
	7, // 7: iwebgw.iwebgw.IWebGWDisconnectWeb:output_type -> iwebgw.IWebGWDisconnectWebRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_iwebgw_proto_init() }
func file_iwebgw_proto_init() {
	if File_iwebgw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iwebgw_proto_rawDesc), len(file_iwebgw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iwebgw_proto_goTypes,
		DependencyIndexes: file_iwebgw_proto_depIdxs,
		MessageInfos:      file_iwebgw_proto_msgTypes,
	}.Build()
	File_iwebgw_proto = out.File
	file_iwebgw_proto_goTypes = nil
	file_iwebgw_proto_depIdxs = nil
}
